[FILTER]
SHELL
IRC
ZN
GT
FILTER
JIMCO
LAIN
TOP 1

[APP API]
# OpenAI API Key
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4o-mini"

# Gemini API Key
gemini_api_key = ""
gemini_model_name = "gemini-2.5-flash"

# Deepseek API Key
deepseek_api_key = ""
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
